### PR TITLE
Added Name Change Boolean to Plugin and Config lua

### PR DESCRIPTION
**Pull request by omarocasio**
Able to toggle name change or not

Note this is correct Pull Request please ignore the other one

### CODE REVIEW

**Comment by omarocasio** [comment]
Tested on my server, works perfectly

**Comment by Itokoyamato** [comment]
Thanks for the PR.
Unfortunately, this is not as simple as just disabling the name change.
Steam names are used as an identifier to link users in-game with users on teamspeak.
If you disable the name changing in the way you've done it, the whole system that controls the other user's audio will be broken.

To get rid of any name changing, some more work will be required.

For example, we could have the plugin send the TS UUID to the fivem script and use this identifier instead. Some code rework on both the plugin and the script would be required.

**Comment by omarocasio** [comment]
> Thanks for the PR.
> Unfortunately, this is not as simple as just disabling the name change.
> Steam names are used as an identifier to link users in-game with users on teamspeak.
> If you disable the name changing in the way you've done it, the whole system that controls the other user's audio will be broken.
> To get rid of any name changing, some more work will be required.
> For example, we could have the plugin send the TS UUID to the fivem script and use this identifier instead. Some code rework on both the plugin and the script would be required.

I actually noticed it too during testing few more time, I'll rework with it sending the TS UUID to FiveM, will commit once finished

**Comment by Itokoyamato** [comment]
Switched the system to using UUID in #15

**Pull request closed without merging**
