### PR TITLE
RedM support

### PR DESCRIPTION
**Pull request by CryptoGenics**
Added config and client facial animation support for RedM.

### CODE REVIEW

**Comment by Itokoyamato** [comment]
That looks very interesting. Do you think we could use the new fxmanifest to detect if its gta5 or rdr2 instead of an additional config ?

**Comment by CryptoGenics** [comment]
wow im dumb hold on ill add fxmanifest to this branch

**Comment by CryptoGenics** [comment]
edits should be in the patch https://github.com/CryptoGenics/TokoVOIP_TS3/tree/patch-1

**Comment by CryptoGenics** [comment]
rereading your question, I do not know of a way to detect which game version your using other than a config like this and adding support in fxmanifest for both fivem and redm.

**Comment by Itokoyamato** [comment]
I believe you can get it through `GetConvar("GameName")` which would return gta5 or rdr3. Could be worth testing, i've just seen it in fivem's source code :D

**Pull request merged**
