### PR TITLE
Potential Call Fix

### PR DESCRIPTION
**Pull request by shredxt**
Only the person who hangs up first had the "in call" text removed, this seems to fix it when the other person hangs up too.

### CODE REVIEW

**Comment by Itokoyamato** [comment]
You were almost on the right path, but you just sort of break things nicely :p 
I've fixed the issue [here](https://github.com/Itokoyamato/TokoVOIP_TS3/commit/2a71ab6ca6c9af6fd86ec6fa6f828164b1f1b6c0)

**Comment by shredxt** [comment]
Oops haha, I removed the incorrect "fix" from the FiveM reply to avoid confusion. Thanks for getting this sorted!

**Comment by Itokoyamato** [comment]
Yeah no worries, thanks for helping out until I could fix it.
To give you context, you don't exactly break anything.
I had a condition to avoid updating data if the channel was empty and destroyed, but the event to update the very last player that left the channel was after that condition.
So I moved it up.
In your case, since you changed the code to not actually delete the channel, but rather remove it's ID, the condition was ignored and player was updated. The main issue with your change is that the channel is not totally deleted, so some data unused data gets left behind.

**Comment by shredxt** [comment]
Ah, I see, I only started learning how to code a few months ago so your insight is extremely useful. I joined the dev team at Revolution and it's been great to work on new resources to add to the server

**Pull request closed without merging**
